const {test}=require('node:test'),assert=require('node:assert/strict');
const api=require('./access-api.js');
function mock(responses){const calls=[];global.fetch=async(url,options)=>{calls.push({url,options});const r=responses.shift();assert.ok(r,'Unexpected request');return {ok:r.status<400,status:r.status,json:async()=>r.data};};return calls;}
const admin={url:'/api/acessos',method:'POST',headers:{authorization:'Bearer session','x-empresa-id':'empresa-b'}};
const control={url:'/api/controle',method:'POST',headers:{authorization:'Bearer session'}};
const body={action:'usuario_criar',usuario:{empresa_id:'empresa-b',nome:'Pessoa',usuario:'PESSOA',email:'pessoa@example.com'},password:'uma-senha-12345',modulos:['locacao']};
test('tenant admin list is scoped to the verified company',async()=>{const calls=mock([{status:200,data:true},{status:200,data:{empresas:[]}}]);await api({...admin,method:'GET'},null);assert.ok(calls[0].url.endsWith('acesso_gerenciar_usuarios'));assert.ok(calls[1].url.endsWith('acessos_empresa_painel'));assert.deepEqual(JSON.parse(calls[1].options.body),{p_empresa:'empresa-b'});});
test('operator cannot manage users',async()=>{const calls=mock([{status:200,data:false}]);await assert.rejects(api(admin,body),e=>e.status===403);assert.equal(calls.length,1);});
test('tenant admin cannot change other companies or licenses',async()=>{for(const payload of [{...body,usuario:{...body.usuario,empresa_id:'other'}},{action:'empresa',empresa:{}}]){const calls=mock([{status:200,data:true}]);await assert.rejects(api(admin,payload),e=>e.status===403);assert.equal(calls.length,1);}});
test('control verifies developer role without requiring selected company',async()=>{let calls=mock([{status:200,data:false}]);await assert.rejects(api({...control,method:'GET'}),e=>e.status===403);assert.ok(calls[0].url.endsWith('acesso_desenvolvedor'));calls=mock([{status:200,data:true},{status:200,data:{empresas:[]}}]);await api({...control,method:'GET'});assert.ok(calls[1].url.endsWith('acessos_painel'));});
test('missing key does not prevent editing existing user',async()=>{delete process.env.SUPABASE_SERVICE_ROLE_KEY;mock([{status:200,data:true},{status:200,data:'user'}]);assert.equal(await api(admin,{action:'usuario_editar',usuario:{id:'user',empresa_id:'empresa-b'},modulos:['locacao']}),'user');mock([{status:200,data:true}]);await assert.rejects(api(admin,body),e=>e.status===503);});
test('new account validates tenant permissions before using administrative key',async()=>{process.env.SUPABASE_SERVICE_ROLE_KEY='server-only';const calls=mock([{status:200,data:true},{status:200,data:null},{status:200,data:{id:'new-user'}},{status:200,data:'profile'}]);assert.equal(await api(admin,body),'profile');assert.ok(calls[1].url.endsWith('acessos_validar_usuario'));assert.equal(calls[2].options.headers.Authorization,'Bearer server-only');assert.equal(calls[3].options.headers.Authorization,'Bearer session');assert.ok(!calls[3].options.body.includes(body.password));});
test('failed profile creation compensates new Auth account',async()=>{process.env.SUPABASE_SERVICE_ROLE_KEY='server-only';const calls=mock([{status:200,data:true},{status:200,data:null},{status:200,data:{id:'new-user'}},{status:403,data:{code:'42501'}},{status:200,data:null}]);await assert.rejects(api(admin,body),e=>e.status===403);assert.equal(calls[4].options.method,'DELETE');});
test('routing and protected pages follow new roles',async()=>{const {canOpen,entryDestination}=await import('./access-policy.js');const c={schemaVersion:2,developer:false,canManageCompany:false,company:{id:'b'},companies:[{id:'b'}],modules:['locacao']};assert.equal(entryDestination(c),'dashboard.html');assert.equal(entryDestination({...c,companies:[{id:'a'},{id:'b'}],company:null}),'modulos.html');assert.equal(entryDestination({...c,developer:true}),'controle.html');assert.equal(canOpen(c,'/financeiro.html'),true);for(const page of ['empresa','acessos','controle'])assert.equal(canOpen(c,'/'+page+'.html'),false);assert.equal(canOpen({...c,canManageCompany:true},'/acessos.html'),true);assert.equal(canOpen({...c,canManageCompany:true},'/controle.html'),false);});
