const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('./test-tools/node_modules/@electric-sql/pglite');
const dev='10000000-0000-0000-0000-000000000001',user='10000000-0000-0000-0000-000000000002';
test('database: tenant isolation, licenses, user grants and developer-only management',async()=>{
 const db=new PGlite();
 try {
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public,storage to authenticated,anon;
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant all on storage.objects to authenticated,anon;
 create table storage.buckets(id text primary key,public boolean);
 insert into auth.users values('${dev}','alquilerentcar@gmail.com',now()),('${user}','client@example.com',now());`);
 let base=fs.readFileSync(__dirname+'/multiempresa_setup.sql','utf8').split('-- Acrescenta empresa_id')[0].replace('create extension if not exists pgcrypto;','');
 await db.exec(base);
 await db.exec(`create table public.clientes(id uuid primary key default gen_random_uuid(),nome text,empresa_id uuid references public.empresas(id));
 create table public.locacoes(id uuid primary key default gen_random_uuid(),cliente_id uuid references public.clientes(id),empresa_id uuid references public.empresas(id));
 create table public.pagamentos_locacao(id uuid primary key default gen_random_uuid(),locacao_id uuid references public.locacoes(id),empresa_id uuid references public.empresas(id));
 create table public.certificados_digitais(id uuid primary key default gen_random_uuid(),arquivo_path text,empresa_id uuid references public.empresas(id));`);
 const migration=fs.readFileSync(__dirname+'/acessos_setup.sql','utf8');await db.exec(migration);await db.exec(migration);
 const owner=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0])[0];
 await owner(dev);assert.equal(await scalar('select public.acesso_desenvolvedor()'),true);
 const a=await scalar("select id from public.empresas where cnpj='54135275000161'");
 const b=await scalar('select public.acessos_salvar_empresa($1,$2)',[{nome_fantasia:'Empresa B',razao_social:'Empresa B LTDA',cnpj:'12345678000190',licenca_ativa:true},['locacao','financeiro']]);
 const profile=await scalar('select public.acessos_salvar_usuario($1,$2)',[{empresa_id:b,auth_user_id:user,nome:'Cliente Teste',usuario:'CLIENTE',administrador:true,ativo:true},['locacao']]);
 const aClient=await scalar('insert into public.clientes(empresa_id,nome) values($1,$2) returning id',[a,'Alquiler']);
 const bClient=await scalar('insert into public.clientes(empresa_id,nome) values($1,$2) returning id',[b,'Empresa B']);
 await owner(user);assert.equal(await scalar('select public.acesso_desenvolvedor()'),false);
 assert.deepEqual((await db.query('select nome from public.clientes')).rows,[{nome:'Empresa B'}]);
 assert.equal(await scalar("select public.acesso_modulo($1,'financeiro')",[b]),false);
 await assert.rejects(db.query('select public.acessos_painel()'),/Somente o desenvolvedor/);
 await assert.rejects(db.query('update public.empresas set licenca_ativa=false where id=$1',[b]),/permission denied/);
 await assert.rejects(db.query('insert into public.clientes(empresa_id,nome) values($1,$2)',[a,'Ataque']),/row-level security/);
 await assert.rejects(db.query('insert into public.locacoes(empresa_id,cliente_id) values($1,$2)',[b,aClient]),/fora da empresa/);
 await db.query('insert into public.locacoes(empresa_id,cliente_id) values($1,$2)',[b,bClient]);
 await assert.rejects(db.query('insert into public.pagamentos_locacao(empresa_id) values($1)',[b]),/row-level security/);
 assert.equal(await scalar('select public.acesso_arquivo($1,$2)',['documentos-clientes',aClient+'/doc.pdf']),false);
 assert.equal(await scalar('select public.acesso_arquivo($1,$2)',['documentos-clientes',bClient+'/doc.pdf']),true);
 await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['documentos-clientes',bClient+'/doc.pdf']);
 await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['documentos-clientes',aClient+'/doc.pdf']),/row-level security/);
 await owner(dev);
 await assert.rejects(db.query('select public.acessos_salvar_usuario($1,$2)',[{id:profile,empresa_id:b,nome:'Cliente Teste',usuario:'CLIENTE',ativo:true},['oficina']]),/não está liberado/);
 await scalar('select public.acessos_salvar_empresa($1,$2)',[{id:b,nome_fantasia:'Empresa B',razao_social:'Empresa B LTDA',cnpj:'12345678000190',licenca_ativa:false},['locacao']]);
 await owner(user);assert.equal(await scalar("select public.acesso_modulo($1,'locacao')",[b]),false);assert.equal((await db.query('select * from public.clientes')).rows.length,0);
 await owner(dev);await scalar('select public.acessos_salvar_empresa($1,$2)',[{id:b,nome_fantasia:'Empresa B',razao_social:'Empresa B LTDA',cnpj:'12345678000190',licenca_ativa:true,licenca_ate:'2000-01-01'},['locacao']]);
 await owner(user);assert.equal(await scalar("select public.acesso_modulo($1,'locacao')",[b]),false);
 await owner(dev);await scalar('select public.acessos_salvar_empresa($1,$2)',[{id:b,nome_fantasia:'Empresa B',razao_social:'Empresa B LTDA',cnpj:'12345678000190',licenca_ativa:true},['locacao']]);
 await scalar('select public.acessos_salvar_usuario($1,$2)',[{id:profile,empresa_id:b,nome:'Cliente Teste',usuario:'CLIENTE',ativo:false},['locacao']]);
 await owner(user);assert.equal(await scalar("select public.acesso_modulo($1,'locacao')",[b]),false);
 assert.equal((await scalar('select public.acessos_contexto($1)',[b])).accessDenied,true);
 } finally {await db.close();}
});
