const fs=require('node:fs'),zlib=require('node:zlib');
const clean=v=>v==null?'':String(v).trim();
const escape=v=>clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'</w:t><w:br/><w:t>');
const units=['zero','um','dois','três','quatro','cinco','seis','sete','oito','nove'];
const teens=['dez','onze','doze','treze','quatorze','quinze','dezesseis','dezessete','dezoito','dezenove'];
const tens=['','','vinte','trinta','quarenta','cinquenta','sessenta','setenta','oitenta','noventa'];
const hundreds=['','cento','duzentos','trezentos','quatrocentos','quinhentos','seiscentos','setecentos','oitocentos','novecentos'];
function words(n){if(n<0||!Number.isSafeInteger(n))return String(n);if(n<10)return units[n];if(n<20)return teens[n-10];if(n<100)return tens[Math.floor(n/10)]+(n%10?' e '+words(n%10):'');if(n===100)return 'cem';if(n<1000)return hundreds[Math.floor(n/100)]+(n%100?' e '+words(n%100):'');if(n<1000000)return (n<2000?'mil':words(Math.floor(n/1000))+' mil')+(n%1000?(n%1000<100?' e ':' ')+words(n%1000):'');return String(n);}
function money(v){let text=clean(v);if(text.includes(','))text=text.replace(/\./g,'').replace(',','.');if(!text||!Number.isFinite(Number(text)))return '';const total=Math.round(Number(text)*100),reais=Math.floor(total/100),cents=total%100;return words(reais)+(reais===1?' real':' reais')+(cents?' e '+words(cents)+(cents===1?' centavo':' centavos'):'');}
function prepare(input){const data={...input};for(const name of ['valor_diaria','valor_caucao','valor_parcela_caucao'])if(!data[name+'_extenso'])data[name+'_extenso']=money(data[name]);if(!data.prazo_dias_extenso&&/^\d+$/.test(clean(data.prazo_dias)))data.prazo_dias_extenso=words(Number(data.prazo_dias));return data;}
function filled(data){return (data.modelo_blocos||[]).map(block=>{const source=block.runs||[],text=source.map(r=>String(r.text||'')).join(''),styles=[];for(const run of source)for(const char of String(run.text||''))for(let i=0;i<char.length;i++)styles.push(run);const runs=[];let cursor=0;const append=(value,style)=>{const props={...style,text:value},last=runs.at(-1);if(last&&JSON.stringify({...last,text:''})===JSON.stringify({...props,text:''}))last.text+=value;else runs.push(props);};const range=(start,end)=>{for(let i=start;i<end;i++)append(text[i],styles[i]);};for(const match of text.matchAll(/\{\{\s*([a-zA-Z][a-zA-Z0-9_]*)\s*\}\}/g)){range(cursor,match.index);append(clean(data[match[1]]),styles[match.index]);cursor=match.index+match[0].length;}range(cursor,text.length);return {align:block.align||'left',runs};});}
function richXml(data){const paragraphs=filled(data).map(block=>{const align=({left:'left',center:'center',right:'right',justify:'both'})[block.align]||'left';const runs=block.runs.map(run=>{const size=Math.trunc(Math.min(24,Math.max(8,Number(run.size)||12)))*2;return '<w:r><w:rPr>'+(run.bold?'<w:b/>':'')+(run.italic?'<w:i/>':'')+(run.underline?'<w:u w:val="single"/>':'')+'<w:sz w:val="'+size+'"/></w:rPr><w:t xml:space="preserve">'+escape(run.text)+'</w:t></w:r>';}).join('');return '<w:p><w:pPr><w:jc w:val="'+align+'"/></w:pPr>'+runs+'</w:p>';}).join('');return '<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+paragraphs+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="2280" w:right="1140" w:bottom="1140" w:left="1700"/></w:sectPr></w:body></w:document>';}
function unzip(buffer){let end=buffer.length-22;while(end>=Math.max(0,buffer.length-65557)&&buffer.readUInt32LE(end)!==0x06054b50)end--;if(end<0)throw Error('Modelo Word inválido.');const count=buffer.readUInt16LE(end+10),files=[];let pos=buffer.readUInt32LE(end+16);for(let i=0;i<count;i++){if(buffer.readUInt32LE(pos)!==0x02014b50)throw Error('Diretório Word inválido.');const method=buffer.readUInt16LE(pos+10),size=buffer.readUInt32LE(pos+20),nameLen=buffer.readUInt16LE(pos+28),extra=buffer.readUInt16LE(pos+30),comment=buffer.readUInt16LE(pos+32),offset=buffer.readUInt32LE(pos+42),name=buffer.subarray(pos+46,pos+46+nameLen).toString('utf8'),start=offset+30+buffer.readUInt16LE(offset+26)+buffer.readUInt16LE(offset+28),packed=buffer.subarray(start,start+size);if(![0,8].includes(method))throw Error('Compressão Word incompatível.');files.push({name,content:method===8?zlib.inflateRawSync(packed):packed});pos+=46+nameLen+extra+comment;}return files;}
function crc32(buffer){let crc=0xffffffff;for(const value of buffer){crc^=value;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function zip(files){const parts=[],central=[];let offset=0;for(const file of files){const name=Buffer.from(file.name),raw=Buffer.from(file.content),packed=zlib.deflateRawSync(raw),crc=crc32(raw),header=Buffer.alloc(30),entry=Buffer.alloc(46);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(8,8);header.writeUInt32LE(crc,14);header.writeUInt32LE(packed.length,18);header.writeUInt32LE(raw.length,22);header.writeUInt16LE(name.length,26);entry.writeUInt32LE(0x02014b50);entry.writeUInt16LE(20,4);entry.writeUInt16LE(20,6);entry.writeUInt16LE(0x800,8);entry.writeUInt16LE(8,10);entry.writeUInt32LE(crc,16);entry.writeUInt32LE(packed.length,20);entry.writeUInt32LE(raw.length,24);entry.writeUInt16LE(name.length,28);entry.writeUInt32LE(offset,42);parts.push(header,name,packed);central.push(entry,name);offset+=header.length+name.length+packed.length;}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...parts,directory,end]);}
function documentXml(text,data){text=text.replace(/Alquiler Rent a Car(?: LTDA\.?)?/gi,'{{ empresa_razao_social }}').replace(/Alquiler/gi,'{{ empresa_razao_social }}');text=text.replace(/<w:p[ >][\s\S]*?<\/w:p>/g,p=>p.replace(/<[^>]+>/g,'').trim().startsWith('LOCADORA:')?'<w:p><w:r><w:t>LOCADORA: {{ empresa_razao_social }}, inscrita no CNPJ nº {{ empresa_cnpj }}, com sede em {{ empresa_endereco }}, e-mail {{ empresa_email }}, telefone {{ empresa_telefone }}, doravante denominada LOCADORA.</w:t></w:r></w:p>':p);return text.replace(/R\$\{\{ multa_atraso_diaria \}\}/g,'{{ multa_atraso_diaria }}').replace(/ASSINATURA DO LOCADOR|ASSINATURA DA LOCADORA/g,m=>m+'</w:t><w:br/><w:t>{{ empresa_razao_social }}').replace(/ASSINATURA DO LOCATÁRIO/g,'ASSINATURA DO LOCATÁRIO</w:t><w:br/><w:t>{{ nome_locatario }}').replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g,(_,name)=>escape(data[name]));}
function paragraphs(xml){const decode=s=>s.replace(/&#x([a-f0-9]+);/gi,(_,v)=>String.fromCodePoint(parseInt(v,16))).replace(/&#(\d+);/g,(_,v)=>String.fromCodePoint(Number(v))).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');return [...xml.matchAll(/<w:p(?:\s[^>]*)?>[\s\S]*?<\/w:p>/g)].map(m=>{let text='';for(const node of m[0].matchAll(/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>|<w:tab\b[^>]*\/>|<w:br\b[^>]*\/>/g))text+=node[1]!=null?decode(node[1]):node[0].startsWith('<w:tab')?'\t':'\n';return text.trim();}).filter(Boolean);}
function generate(input,template,preview=false){const data=prepare(input),files=unzip(fs.readFileSync(template));let xml;for(const file of files){if(!file.name.endsWith('.xml'))continue;let text=file.content.toString('utf8');if(file.name==='word/document.xml'){text=data.modelo_blocos?.length?richXml(data):documentXml(text,data);xml=text;}else text=text.replace(/Alquiler Rent a Car(?: LTDA\.?)?/gi,'{{ empresa_razao_social }}').replace(/Alquiler/gi,'{{ empresa_razao_social }}').replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g,(_,name)=>escape(data[name]));file.content=Buffer.from(text);}if(!xml)throw Error('Texto do modelo Word não encontrado.');return preview?Buffer.from(JSON.stringify({paragraphs:paragraphs(xml),formatacao:filled(data),modelo_versao:data.modelo_versao??null})):zip(files);}
module.exports={generate,filled,words,money,unzip};
