import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
import {requireAuth,bindLogout} from "./auth-guard.js";
const db=createClient("https://xtelzwclrzzlsqjecscl.supabase.co","sb_publishable_37VAv7_GhtRLum-WVwMv0w_EiD0HqZ3");await requireAuth(db);bindLogout(db);
const $=s=>document.querySelector(s),state={rows:[],clients:[],cars:[]};
const clientName=id=>state.clients.find(x=>x.id===id)?.nome_completo||"Cliente indisponível";
const carName=id=>{const x=state.cars.find(x=>x.id===id);return x?`${x.placa} · ${x.marca||""} ${x.modelo||""}`:"Veículo indisponível"};
function status(row){return row.contrato_status||"Rascunho"}
function number(row){return row.contrato_numero||`LOC-${new Date(row.criado_em).getFullYear()}-${row.id.slice(0,8).toUpperCase()}`}
async function openContract(row,button){if(!row.contrato_gerado_em)return location.href=`contrato.html?locacao=${encodeURIComponent(row.id)}`;const previous=button.textContent;button.disabled=true;button.textContent="Abrindo PDF…";const {data,error}=await db.from("documentos_locacao").select("arquivo_assinado_path,arquivo_original_path,versao").eq("locacao_id",row.id).eq("tipo","contrato_locacao").order("versao",{ascending:false}).limit(1).maybeSingle();if(error||!data){button.disabled=false;button.textContent=previous;return alert(error?.message||"O PDF definitivo não foi encontrado nos registros.")}const path=data.arquivo_assinado_path||data.arquivo_original_path,{data:signed,error:signedError}=await db.storage.from("documentos-contratuais").createSignedUrl(path,3600);if(signedError||!signed?.signedUrl){button.disabled=false;button.textContent=previous;return alert(signedError?.message||"Não foi possível abrir o PDF.")}location.href=signed.signedUrl}
function render(){const search=$("#contracts-search");let q=search.value.trim().toLocaleLowerCase("pt-BR");if(q==="alquilerentcar@gmail.com"){q="";search.value=""}const filter=$("#contracts-status").value,rows=state.rows.filter(x=>(filter==="todos"||status(x)===filter)&&`${number(x)} ${clientName(x.cliente_id)} ${carName(x.carro_id)}`.toLocaleLowerCase("pt-BR").includes(q));$("#contracts-total").textContent=state.rows.length;$("#contracts-draft").textContent=state.rows.filter(x=>status(x)==="Rascunho").length;$("#contracts-waiting").textContent=state.rows.filter(x=>["Gerado","PDF gerado","Enviado"].includes(status(x))).length;$("#contracts-signed").textContent=state.rows.filter(x=>["Assinado","Arquivado"].includes(status(x))).length;$("#contracts-count").textContent=`${rows.length} de ${state.rows.length} contratos`;const body=$("#contracts-body");body.replaceChildren();for(const row of rows){const tr=document.createElement("tr");for(const value of[number(row),clientName(row.cliente_id),carName(row.carro_id),status(row),row.status_assinatura||"Pendente",row.contrato_versao||1]){const td=document.createElement("td");td.textContent=value;tr.append(td)}const actions=document.createElement("td"),open=document.createElement("button");open.textContent=row.contrato_gerado_em?"Abrir PDF":"Editar rascunho";open.onclick=()=>openContract(row,open);actions.append(open);tr.append(actions);body.append(tr)}$("#contracts-empty").classList.toggle("hidden",rows.length>0)}
async function load(){const[rows,clients,cars]=await Promise.all([db.from("locacoes").select("*").order("criado_em",{ascending:false}),db.from("clientes").select("id,nome_completo"),db.from("carros").select("id,placa,marca,modelo")]);const error=rows.error||clients.error||cars.error;if(error){$("#contracts-count").textContent=error.message;return}state.rows=rows.data||[];state.clients=clients.data||[];state.cars=cars.data||[];render()}
$("#refresh-contracts").onclick=load;$("#contracts-search").oninput=render;$("#contracts-status").onchange=render;await load();
