import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {requireAuth,bindLogout} from './auth-guard.js';
const db=createClient('https://xtelzwclrzzlsqjecscl.supabase.co','sb_publishable_37VAv7_GhtRLum-WVwMv0w_EiD0HqZ3');
await requireAuth(db);bindLogout(db);
const $=s=>document.querySelector(s),form=$('#company-form'),context=window.alquilerContext;
let logoData=context.company.logo_url||'';
function notify(message,error=false){const t=$('#toast');t.textContent=message;t.classList.toggle('error',error);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function renderLogo(){const p=$('#company-logo-preview');if(logoData){p.textContent='';p.style.backgroundImage=`url("${logoData.replace(/"/g,'%22')}")`;p.classList.add('has-logo')}else{p.textContent=(form.elements.nome_fantasia.value||'E').trim().charAt(0).toUpperCase();p.style.backgroundImage='';p.classList.remove('has-logo')}}
async function loadCertificates(){const select=$('#company-existing-certificate');let query=db.from('certificados_digitais').select('id,titular,identificador,emissor,valido_ate').order('valido_ate',{ascending:false});if(context.company.id)query=query.eq('empresa_id',context.company.id);const {data,error}=await query;if(error||!data?.length){select.innerHTML='<option value="">Nenhum certificado cadastrado</option>';return}select.innerHTML='<option value="">Selecione um certificado</option>'+data.map((c,i)=>`<option value="${i}">${c.titular} · ${c.identificador||'sem CNPJ'} · válido até ${c.valido_ate||'—'}</option>`).join('');select._certificates=data}
function load(){for(const n of['razao_social','nome_fantasia','cnpj','telefone','email','endereco','papel_timbrado_nome'])if(form.elements[n])form.elements[n].value=context.company[n]||'';renderLogo();loadCertificates();if(!context.user.administrador){form.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);$('#save-company').disabled=true;notify('Somente administradores podem alterar os dados da empresa.',true)}}
$('#use-existing-certificate').onclick=()=>{const select=$('#company-existing-certificate');if(select.value==='')return notify('Selecione um certificado cadastrado.',true);const cert=select._certificates?.[Number(select.value)];if(!cert)return;form.elements.razao_social.value=cert.titular||form.elements.razao_social.value;if(/^\d{14}$/.test(cert.identificador||''))form.elements.cnpj.value=cert.identificador;$('#company-certificate-status').textContent=`Dados vinculados ao certificado emitido por ${cert.emissor||'emissor não informado'}.`;notify('Dados do certificado carregados.')};
$('#company-logo').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>500*1024)return notify('Use um logo de até 500 KB.',true);logoData=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});renderLogo()});
$('#remove-company-logo').onclick=()=>{logoData='';$('#company-logo').value='';renderLogo()};
$('#company-stationery').addEventListener('change',e=>{form.elements.papel_timbrado_nome.value=e.target.files[0]?.name||''});
form.addEventListener('submit',async e=>{e.preventDefault();if(!context.user.administrador)return notify('Somente administradores podem salvar.',true);const button=$('#save-company'),payload=Object.fromEntries(new FormData(form));payload.cnpj=String(payload.cnpj||'').replace(/\D/g,'');payload.logo_url=logoData;button.disabled=true;button.textContent='Salvando…';let companyId=context.company.id;if(!companyId){const found=await db.from('empresas').select('id').eq('cnpj',context.company.cnpj).maybeSingle();companyId=found.data?.id}if(!companyId){button.disabled=false;button.textContent='Salvar alterações';return notify('Empresa não localizada no Supabase.',true)}const {data,error}=await db.from('empresas').update(payload).eq('id',companyId).select().single();button.disabled=false;button.textContent='Salvar alterações';if(error)return notify(error.message||'Não foi possível salvar.',true);localStorage.setItem('bgsys:empresa-cache',JSON.stringify(data));notify('Dados salvos para todos os usuários da empresa.');setTimeout(()=>location.reload(),700)});
load();
