import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {PDFDocument} from 'https://esm.sh/pdf-lib@1.17.1';
import {requireAuth,bindLogout} from './auth-guard.js';
import {BRANDING_BUCKET,applyCompanyTheme} from './empresa-branding.js';
const db=createClient('https://xtelzwclrzzlsqjecscl.supabase.co','sb_publishable_37VAv7_GhtRLum-WVwMv0w_EiD0HqZ3');
await requireAuth(db);bindLogout(db);
const $=s=>document.querySelector(s),form=$('#company-form'),context=window.alquilerContext;
let logoData=context.company.logo_url||'',pendingPdf=null,removePdf=false,previewUrl='',validating=false;
function notify(message,error=false){const t=$('#toast');t.textContent=message;t.classList.toggle('error',error);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),5000)}
function renderLogo(){const p=$('#company-logo-preview');p.textContent=logoData?'':(form.elements.nome_fantasia.value||'E').trim().charAt(0).toUpperCase();p.style.backgroundImage=logoData?`url("${logoData.replace(/"/g,'%22')}")`:'';p.classList.toggle('has-logo',Boolean(logoData))}
function clearPreview(){if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';$('#stationery-preview').hidden=true;$('#stationery-preview').removeAttribute('src')}
function preview(blob){clearPreview();previewUrl=URL.createObjectURL(blob);$('#stationery-preview').src=previewUrl;$('#stationery-preview').hidden=false}
async function loadCertificates(){const select=$('#company-existing-certificate');const {data,error}=await db.from('certificados_digitais').select('titular,identificador,emissor,valido_ate').order('valido_ate',{ascending:false});select.replaceChildren(new Option(error?'Não foi possível carregar certificados':'Selecione um certificado',''));for(const [i,c] of(data||[]).entries())select.add(new Option(`${c.titular} · ${c.identificador||'sem CNPJ'}`,String(i)));select._certificates=data||[]}
for(const n of ['razao_social','nome_fantasia','cnpj','telefone','email','endereco','papel_timbrado_nome','cor_primaria','cor_sidebar','cor_fundo'])form.elements[n].value=context.company[n]||({cor_primaria:'#2864da',cor_sidebar:'#111e32',cor_fundo:'#f5f7fb'}[n]||'');
renderLogo();loadCertificates();
$('#stationery-status').textContent=context.company.papel_timbrado_path?'Papel timbrado salvo.': 'Nenhum PDF armazenado. Envie o arquivo para usá-lo nos novos documentos.';
for(const name of ['cor_primaria','cor_sidebar','cor_fundo'])form.elements[name].oninput=()=>applyCompanyTheme(Object.fromEntries(['cor_primaria','cor_sidebar','cor_fundo'].map(n=>[n,form.elements[n].value])));
form.elements.nome_fantasia.oninput=renderLogo;
$('#use-existing-certificate').onclick=()=>{const select=$('#company-existing-certificate');if(select.value==='')return notify('Selecione um certificado.',true);const cert=select._certificates[Number(select.value)];form.elements.razao_social.value=cert.titular||form.elements.razao_social.value;if(/^\d{14}$/.test(cert.identificador||''))form.elements.cnpj.value=cert.identificador;$('#company-certificate-status').textContent='Dados carregados. Salve as alterações para confirmar.'};
$('#company-logo').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>500*1024)throw new Error('Use PNG, JPG ou WebP de até 500 KB.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas'),scale=Math.min(1,600/bitmap.width,600/bitmap.height);canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();logoData=canvas.toDataURL('image/png');renderLogo()}catch(error){e.target.value='';notify(error.message||'Imagem inválida.',true)}};
$('#remove-company-logo').onclick=()=>{logoData='';$('#company-logo').value='';renderLogo()};
$('#company-stationery').onchange=async e=>{const file=e.target.files[0];if(!file)return;validating=true;try{if(file.size>10*1024*1024)throw new Error('O limite do papel timbrado é 10 MB.');const bytes=await file.arrayBuffer();if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw new Error('Escolha um arquivo PDF.');const pdf=await PDFDocument.load(bytes);if(pdf.getPageCount()!==1)throw new Error('Use um PDF de uma única página.');const {width,height}=pdf.getPage(0).getSize();if(Math.abs(width-595.28)>12||Math.abs(height-841.89)>12)throw new Error('Use uma página A4 na orientação vertical.');pendingPdf=new File([bytes],file.name,{type:'application/pdf'});removePdf=false;form.elements.papel_timbrado_nome.value=file.name;$('#stationery-status').textContent='Arquivo validado. Salve as alterações para aplicar.';preview(pendingPdf)}catch(error){e.target.value='';notify(error.message||'PDF inválido ou protegido por senha.',true)}finally{validating=false}};
$('#preview-stationery').onclick=async()=>{try{if(pendingPdf)return preview(pendingPdf);if(removePdf||!context.company.papel_timbrado_path)return notify('Escolha e salve um papel timbrado primeiro.');const {data,error}=await db.storage.from(BRANDING_BUCKET).download(context.company.papel_timbrado_path);if(error)throw error;preview(data)}catch{notify('Não foi possível abrir o papel timbrado.',true)}};
$('#remove-stationery').onclick=()=>{pendingPdf=null;removePdf=true;$('#company-stationery').value='';form.elements.papel_timbrado_nome.value='';clearPreview();$('#stationery-status').textContent='Ao salvar, novos documentos usarão uma página neutra.'};
form.onsubmit=async e=>{e.preventDefault();if(!context.canManageCompany)return notify('Somente administradores podem salvar.',true);if(validating)return notify('Aguarde a validação do PDF.',true);const button=$('#save-company');button.disabled=true;button.textContent='Salvando…';let uploaded='';try{
 const payload={};for(const n of ['razao_social','nome_fantasia','cnpj','telefone','email','endereco','cor_primaria','cor_sidebar','cor_fundo'])payload[n]=form.elements[n].value.trim();payload.cnpj=payload.cnpj.replace(/\D/g,'');if(payload.cnpj.length!==14)throw new Error('Informe um CNPJ com 14 dígitos.');payload.logo_url=logoData;
 payload.papel_timbrado_path=context.company.papel_timbrado_path||null;payload.papel_timbrado_nome=context.company.papel_timbrado_nome||null;
 if(pendingPdf){uploaded=`${context.company.id}/${crypto.randomUUID()}.pdf`;const {error}=await db.storage.from(BRANDING_BUCKET).upload(uploaded,pendingPdf,{contentType:'application/pdf',upsert:false});if(error)throw error;payload.papel_timbrado_path=uploaded;payload.papel_timbrado_nome=pendingPdf.name}
 else if(removePdf){payload.papel_timbrado_path=null;payload.papel_timbrado_nome=null}
 const {data,error}=await db.from('empresas').update(payload).eq('id',context.company.id).select().single();if(error)throw error;
 // Arquivos anteriores são mantidos para não invalidar referências existentes.
 context.company=data;pendingPdf=null;removePdf=false;notify('Configurações salvas para esta empresa.');setTimeout(()=>location.reload(),700);
 }catch(error){if(uploaded)await db.storage.from(BRANDING_BUCKET).remove([uploaded]);notify(/cor_primaria|cor_sidebar|cor_fundo|bucket|schema cache/i.test(error.message||'')?'Aplique ajustes_empresa_contratos.sql no Supabase para ativar as novas cores.':error.message||'Não foi possível salvar.',true)}finally{button.disabled=false;button.textContent='Salvar alterações'}};
window.addEventListener('pagehide',clearPreview);
