const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
let PGlite;try{({PGlite}=require('./test-tools/node_modules/@electric-sql/pglite'));}catch{({PGlite}=require('../acessos-stage/test-tools/node_modules/@electric-sql/pglite'));}
const ids={dev:'10000000-0000-0000-0000-000000000001',admin:'10000000-0000-0000-0000-000000000002',operator:'10000000-0000-0000-0000-000000000003',newUser:'10000000-0000-0000-0000-000000000004'};
test('Etapa 1: tenant administrator, developer control, login selection and revocation',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
   create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth,public,storage to authenticated,anon;
   create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant all on storage.objects to authenticated,anon;
   create table storage.buckets(id text primary key,public boolean);
   insert into auth.users values('${ids.dev}','alquilerentcar@gmail.com',now()),('${ids.admin}','admin@example.com',now()),('${ids.operator}','operator@example.com',now()),('${ids.newUser}','new@example.com',now());`);
  const base=fs.readFileSync(__dirname+'/multiempresa_setup.sql','utf8').split('-- Acrescenta empresa_id')[0].replace('create extension if not exists pgcrypto;','');await db.exec(base);
  await db.exec(`create table public.clientes(id uuid primary key default gen_random_uuid(),nome text,empresa_id uuid references public.empresas(id));
   create table public.locacoes(id uuid primary key default gen_random_uuid(),cliente_id uuid references public.clientes(id),empresa_id uuid references public.empresas(id));
   create table public.pagamentos_locacao(id uuid primary key default gen_random_uuid(),empresa_id uuid references public.empresas(id));`);
  await db.exec(fs.readFileSync(__dirname+'/acessos_setup.sql','utf8'));
  const migration=fs.readFileSync(__dirname+'/etapa1_acessos.sql','utf8');await db.exec(migration);await db.exec(migration);
  const as=async user=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role authenticated');};
  const scalar=async(q,args=[])=>Object.values((await db.query(q,args)).rows[0])[0];
  const saveUser=(user,mods=['locacao'])=>scalar('select public.acessos_salvar_usuario($1,$2)',[user,mods]);
  await as(ids.dev);
  const a=await scalar("select id from public.empresas where cnpj='54135275000161'");
  const company={nome_fantasia:'Empresa B',razao_social:'EMPRESA B',cnpj:'12345678000190',licenca_ativa:true};
  const b=await scalar('select public.acessos_salvar_empresa($1,$2)',[company,['locacao']]);
  const adminData={empresa_id:b,auth_user_id:ids.admin,nome:'Administrador B',usuario:'ADMINB',administrador:true,ativo:true};
  const adminId=await saveUser(adminData);
  const opData={empresa_id:b,auth_user_id:ids.operator,nome:'Operador B',usuario:'OPERADOR',administrador:false,ativo:true};
  const operatorId=await saveUser(opData);
  await db.query('insert into public.clientes(empresa_id,nome) values($1,$2),($3,$4)',[a,'Cliente A',b,'Cliente B']);
  const devProfile=await scalar('select id from public.usuarios_empresa where auth_user_id=$1 and empresa_id=$2',[ids.dev,a]);
  await as(ids.admin);
  assert.equal(await scalar('select public.acesso_desenvolvedor()'),false);
  assert.equal(await scalar('select public.acesso_gerenciar_usuarios($1)',[b]),true);
  assert.equal(await scalar('select public.acesso_gerenciar_usuarios($1)',[a]),false);
  const context=await scalar('select public.acessos_contexto(null)');assert.equal(context.schemaVersion,2);assert.equal(context.company.id,b);assert.deepEqual(context.modules,['locacao']);assert.equal(context.canManageCompany,true);
  const panel=await scalar('select public.acessos_empresa_painel($1)',[b]);assert.deepEqual(panel.empresas.map(e=>e.id),[b]);assert.equal(panel.usuarios.length,2);assert.equal(panel.modulos.some(m=>m.codigo==='financeiro'),false);
  await assert.rejects(db.query('select public.acessos_painel()'),/Somente o desenvolvedor/);
  await assert.rejects(db.query('select public.acessos_empresa_painel($1)',[a]),/Somente o desenvolvedor/);
  await assert.rejects(db.query('select public.acessos_salvar_empresa($1,$2)',[{...company,id:b,licenca_ativa:false},['locacao']]),/Somente o desenvolvedor/);
  await assert.rejects(db.query('update public.empresas set licenca_ativa=false where id=$1',[b]),/permission denied/);
  await assert.rejects(saveUser({...adminData,id:adminId,ativo:false}),/próprio perfil/);
  await assert.rejects(saveUser({...adminData,id:adminId},[]),/precisam de acesso/);
  await assert.rejects(saveUser({...opData,id:devProfile,empresa_id:a}),/Somente o desenvolvedor/);
  await assert.rejects(saveUser({...opData,id:operatorId},['financeiro']),/não está liberado/);
  const added=await saveUser({empresa_id:b,auth_user_id:ids.newUser,nome:'Novo usuário',usuario:'NOVO',administrador:false,ativo:true});assert.ok(added);
  await saveUser({...opData,id:operatorId,nome:'Operador atualizado'});
  assert.deepEqual((await db.query('select nome from public.clientes')).rows,[{nome:'Cliente B'}]);
  await db.query('insert into public.pagamentos_locacao(empresa_id) values($1)',[b]);
  await assert.rejects(db.query('insert into public.pagamentos_locacao(empresa_id) values($1)',[a]),/row-level security/);
  await as(ids.operator);assert.equal((await scalar('select public.acessos_contexto(null)')).canManageCompany,false);
  await assert.rejects(db.query('select public.acessos_empresa_painel($1)',[b]),/Somente o desenvolvedor/);
  await assert.rejects(saveUser({...opData,id:operatorId,administrador:true}),/Somente o desenvolvedor/);
  await as(ids.dev);
  await saveUser({...adminData,empresa_id:a,usuario:'ADMINA'});
  await as(ids.admin);const multiple=await scalar('select public.acessos_contexto(null)');assert.equal(multiple.companies.length,2);assert.equal(multiple.company,null);assert.equal(multiple.accessDenied,false);assert.equal(multiple.canManageCompany,false);
  assert.equal((await scalar('select public.acessos_contexto($1)',[b])).company.id,b);
  await as(ids.dev);await scalar('select public.acessos_salvar_empresa($1,$2)',[{...company,id:b,licenca_ativa:false},['locacao']]);
  await as(ids.admin);assert.equal(await scalar('select public.acesso_gerenciar_usuarios($1)',[b]),false);await assert.rejects(saveUser({...opData,id:operatorId}),/Somente o desenvolvedor/);
  await as(ids.dev);await scalar('select public.acessos_salvar_empresa($1,$2)',[{...company,id:b},['locacao']]);
  await saveUser({...adminData,id:adminId,ativo:false});await as(ids.admin);assert.equal(await scalar('select public.acesso_gerenciar_usuarios($1)',[b]),false);
 }finally{await db.close();}
});
