import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {requireAuth,bindLogout} from './auth-guard.js';
import {money,localDate,totals} from './frota-core.mjs';
const db=createClient('https://xtelzwclrzzlsqjecscl.supabase.co','sb_publishable_37VAv7_GhtRLum-WVwMv0w_EiD0HqZ3');
await requireAuth(db);bindLogout(db);
const $=s=>document.querySelector(s),company=window.alquilerContext.company;
const section=new URLSearchParams(location.search).get('secao')||'';
let rows=[],history=[],panel={clientes:[],carros:[],periodos:[]},selected=null,busy=false,generation=0;
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const dateLabel=date=>date?date.split('-').reverse().join('/'):'—';
const stamp=value=>new Date(value).toLocaleString('pt-BR',{timeZone:'America/Manaus'});
const nextDate=date=>new Date(Date.parse(date+'T12:00:00Z')+86400000).toISOString().slice(0,10);
const amount=value=>Math.round(Number(value)*100)/100;
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),5000);}
async function rpc(name,args={}){const {data,error}=await db.rpc(name,{p_empresa:company.id,...args});if(error)throw new Error(error.code==='PGRST202'?'O controle de diárias precisa ser ativado no banco.':error.message);return data;}
function metric(label,value){const div=node('div',null,'metric');div.append(node('span',label),node('strong',value));return div;}
$('#finance-date').value=localDate();$('#finance-from').value=localDate();$('#finance-to').value=localDate();
const historyMode=section==='recebidos'||section==='extrato';
$('#finance-history-view').hidden=!historyMode;$('#finance-dues-view').hidden=historyMode;
$('#finance-title').textContent=historyMode?'Recebimentos':section==='contas-receber'?'Contas a receber':'Entradas';
$('#finance-description').textContent=historyMode?'Histórico dos pagamentos registrados para as diárias da frota.':'Controle das diárias: previsto, recebido e saldo por dia.';
$('#finance-daily-tab').setAttribute('aria-current',historyMode?'false':'page');$('#finance-history-tab').setAttribute('aria-current',historyMode?'page':'false');
async function receipts(from,to){let result=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('frota_recebimentos').select('id,grupo_id,competencia,valor,criado_em').eq('empresa_id',company.id).gte('criado_em',from+'T00:00:00-04:00').lt('criado_em',nextDate(to)+'T00:00:00-04:00').order('criado_em',{ascending:false}).order('id',{ascending:false}).range(offset,offset+999);if(error)throw new Error(error.message);result.push(...data);if(data.length<1000)return result;}}
function identity(receipt){const periods=panel.periodos.filter(p=>p.grupo_id===receipt.grupo_id&&localDate(new Date(p.inicio))<=receipt.competencia&&(!p.fim||new Date(p.fim)>new Date(receipt.competencia+'T00:00:00-04:00'))).sort((a,b)=>new Date(b.inicio)-new Date(a.inicio));const period=periods[0];return {cliente:panel.clientes.find(c=>c.id===period?.cliente_id)?.nome||'Cliente não identificado',placa:panel.carros.find(c=>c.id===period?.carro_id)?.placa||'—'};}
function empty(body,cols,text){const tr=node('tr'),td=node('td',text);td.colSpan=cols;td.style.textAlign='center';td.style.padding='36px';tr.append(td);body.append(tr);}
function render(){const q=$('#finance-search').value.trim().toLocaleLowerCase('pt-BR'),filter=$('#finance-status').value,body=$('#finance-dues');body.replaceChildren();const day=$('#finance-date').value;const t=totals(rows);$('#finance-metrics').replaceChildren(metric('Previsto para '+dateLabel(day),money(t.previsto)),metric('Recebido dessas diárias',money(t.recebido)),metric('Saldo a receber',money(t.saldo)),metric('Diárias do dia',String(rows.length)));
 let count=0;for(const row of rows){const balance=amount(Math.max(0,Number(row.diaria)-Number(row.recebido)));const status=balance===0?'Pago':Number(row.recebido)>0?'Parcial':'Pendente';if(!`${row.cliente} ${row.placa}`.toLocaleLowerCase('pt-BR').includes(q)||filter&&status!==filter)continue;const tr=node('tr');for(const value of [row.cliente,row.placa,money(row.diaria),money(row.recebido),money(balance)])tr.append(node('td',value));const statusCell=node('td');statusCell.append(node('span',status,'badge '+(status==='Pago'?'active':'inactive')));tr.append(statusCell);const actions=node('td'),button=node('button','Registrar recebimento','btn btn-quiet');button.disabled=balance<=0||day>localDate();button.onclick=()=>openPayment(row,day);actions.append(button);tr.append(actions);body.append(tr);count++;}if(!count)empty(body,7,rows.length?'Nenhuma diária corresponde aos filtros.':'Nenhuma diária para este dia. Registre a operação atual em Frota e diárias.');
 const historyBody=$('#finance-history');historyBody.replaceChildren();let received=0,shown=0;for(const receipt of history){const who=identity(receipt);if(!`${who.cliente} ${who.placa}`.toLocaleLowerCase('pt-BR').includes(q))continue;const tr=node('tr');for(const value of [stamp(receipt.criado_em),who.cliente,who.placa,dateLabel(receipt.competencia),money(receipt.valor)])tr.append(node('td',value));historyBody.append(tr);received+=Number(receipt.valor);shown++;}if(!shown)empty(historyBody,5,'Nenhum recebimento registrado neste período.');$('#finance-history-summary').textContent=shown+' registro(s) · Total recebido: '+money(received);$('#finance-count').textContent=count+' de '+rows.length+' diária(s)';if(historyMode)$('#finance-metrics').replaceChildren(metric('Recebido no período',money(received)),metric('Pagamentos registrados',String(shown)));}
async function load(){const token=++generation;$('#finance-error').textContent='';$('#finance-refresh').disabled=true;try{const day=$('#finance-date').value,from=$('#finance-from').value,to=$('#finance-to').value;if(!day||!from||!to||from>to)throw new Error('Informe datas válidas; o início deve ser anterior ou igual ao fim.');const [forecast,records,context,legacy]=await Promise.all([rpc('frota_previsto',{p_dia:day}),receipts(from,to),rpc('frota_painel'),db.from('locacoes').select('id').eq('empresa_id',company.id).eq('status','Ativa')]);if(legacy.error)throw new Error(legacy.error.message);if(token!==generation)return;rows=forecast||[];history=records;panel=context;$('#finance-legacy-note').hidden=!legacy.data.length;$('#finance-legacy-note').textContent=legacy.data.length+' locação(ões) ativa(s) do fluxo de contratos ainda precisam ser conciliadas com a Frota. Não somadas automaticamente a estas diárias.';render();}catch(error){if(token!==generation)return;rows=[];history=[];$('#finance-metrics').replaceChildren();$('#finance-dues').replaceChildren();$('#finance-history').replaceChildren();$('#finance-count').textContent='';$('#finance-history-summary').textContent='';$('#finance-error').textContent=error.message;}finally{if(token===generation)$('#finance-refresh').disabled=false;}}
function openPayment(row,day){selected={row,day};$('#finance-payment-form').reset();$('#finance-payment-error').textContent='';$('#finance-payment-client').textContent=row.cliente+' · '+row.placa;$('#finance-payment-description').textContent='Diária de '+dateLabel(day)+' · Saldo: '+money(Number(row.diaria)-Number(row.recebido));$('#finance-payment-value').value=amount(Number(row.diaria)-Number(row.recebido)).toFixed(2);$('#finance-payment-value').max=amount(Number(row.diaria)-Number(row.recebido));$('#finance-payment-dialog').showModal();}
$('#finance-payment-form').onsubmit=async event=>{event.preventDefault();if(busy||!selected)return;const value=Number($('#finance-payment-value').value),balance=amount(Number(selected.row.diaria)-Number(selected.row.recebido));if(!Number.isFinite(value)||value<=0||value>balance){$('#finance-payment-error').textContent='Informe um valor positivo até '+money(balance)+'.';return;}busy=true;$('#finance-payment-save').disabled=true;$('#finance-payment-error').textContent='';try{await rpc('frota_receber',{p_grupo:selected.row.grupo_id,p_dia:selected.day,p_valor:amount(value)});selected=null;$('#finance-payment-dialog').close();notify('Recebimento registrado.');await load();}catch(error){$('#finance-payment-error').textContent=error.message;}finally{busy=false;$('#finance-payment-save').disabled=false;}};
for(const button of document.querySelectorAll('[data-finance-close]'))button.onclick=()=>{if(!busy)$('#finance-payment-dialog').close();};$('#finance-payment-dialog').addEventListener('cancel',event=>{if(busy)event.preventDefault();});
$('#finance-refresh').onclick=load;$('#finance-search').oninput=render;$('#finance-status').onchange=render;for(const id of ['finance-date','finance-from','finance-to'])$('#'+id).onchange=load;
await load();
