import {createClient} from "https://esm.sh/@supabase/supabase-js@2"; import {requireAuth,bindLogout} from "./auth-guard.js";
const db=createClient("https://xtelzwclrzzlsqjecscl.supabase.co","sb_publishable_37VAv7_GhtRLum-WVwMv0w_EiD0HqZ3"); await requireAuth(db); bindLogout(db);
const $=s=>document.querySelector(s),state={rows:[],clients:[],cars:[],editing:null}; let timer;
const money=n=>n==null?"—":Number(n).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}); const date=d=>d?new Date(d).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—";
function toast(t,e=false){const x=$("#toast");x.textContent=t;x.classList.toggle("error",e);x.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>x.classList.remove("show"),4000)}
function fill(el,rows,label){el.replaceChildren(new Option("Selecione",""));rows.forEach(x=>el.add(new Option(label(x),x.id)))}
function clientName(id){return state.clients.find(x=>x.id===id)?.nome_completo||"Cliente indisponível"} function carName(id){const x=state.cars.find(x=>x.id===id);return x?`${x.placa} · ${x.marca||""} ${x.modelo||""}`:"Carro indisponível"}
const plain=v=>v==null?"":String(v); const brl=v=>v==null?"":Number(v).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
function calculateDeposit(){const f=$("#rental-form"),num=name=>Number(f.elements.namedItem(name)?.value)||0,total=Math.max(0,num("valor_caucao")),paid=Math.min(Math.max(0,num("valor_caucao_pago")),total),installments=Math.max(1,Math.trunc(num("numero_parcelas_caucao")||100)),balance=Math.max(0,total-paid),installment=balance/installments,daily=Math.max(0,num("valor_diaria"));f.elements.valor_caucao_pago.value=paid.toFixed(2);f.elements.saldo_caucao.value=balance.toFixed(2);f.elements.numero_parcelas_caucao.value=installments;f.elements.valor_parcela_caucao.value=installment.toFixed(2);f.elements.valor_diaria_com_caucao.value=(daily+installment).toFixed(2)}
function render(){const search=$("#rental-search");let q=search.value.toLocaleLowerCase("pt-BR");if(q.trim()==="alquilerentcar@gmail.com"){q="";search.value=""}const s=$("#rental-status").value,rows=state.rows.filter(x=>(s==="todos"||x.status===s)&&`${clientName(x.cliente_id)} ${carName(x.carro_id)}`.toLocaleLowerCase("pt-BR").includes(q));$("#rental-total").textContent=state.rows.length;$("#rental-active").textContent=state.rows.filter(x=>x.status==="Ativa").length;$("#rental-reserved").textContent=state.rows.filter(x=>x.status==="Reservada").length;$("#rental-closed").textContent=state.rows.filter(x=>x.status==="Encerrada").length;$("#rental-count").textContent=`${rows.length} de ${state.rows.length} locações`;const b=$("#rental-body");b.replaceChildren();for(const x of rows){const tr=document.createElement("tr");const clientCell=document.createElement("td"),clientLink=document.createElement("button");clientLink.className="record-link";clientLink.textContent=clientName(x.cliente_id);clientLink.onclick=()=>location.href=`registros.html?locacao=${encodeURIComponent(x.id)}`;clientCell.append(clientLink);tr.append(clientCell);for(const v of[carName(x.carro_id),date(x.data_inicio),date(x.data_fim),money(x.valor_diaria),money(x.valor_pago),x.status]){const td=document.createElement("td");td.textContent=v;tr.append(td)}const a=document.createElement("td");a.className="row-actions";const records=document.createElement("button");records.textContent="Ver registros";records.onclick=()=>location.href=`registros.html?locacao=${encodeURIComponent(x.id)}`;a.append(records);tr.append(a);b.append(tr)}$("#rental-empty").classList.toggle("hidden",rows.length>0)}
async function load(){const[rs,cs,vs]=await Promise.all([db.from("locacoes").select("*").order("criado_em",{ascending:false}),db.from("clientes").select("id,nome_completo,situacao").order("nome_completo"),db.from("carros").select("*").order("placa")]);const e=rs.error||cs.error||vs.error;if(e)return toast(e.message,true);state.rows=rs.data||[];state.clients=cs.data||[];state.cars=vs.data||[];fill($("#rental-client"),state.clients,x=>x.nome_completo);fill($("#rental-car"),state.cars,x=>carName(x.id));render()}
function open(){state.editing=null;const f=$("#rental-form");f.reset();$("#rental-dialog-title").textContent="Nova locação";f.elements.data_inicio.value=localNow();f.elements.multa_atraso_percentual.value="11";f.elements.numero_parcelas_caucao.value="100";f.elements.valor_caucao_pago.value="0";calculateDeposit();$("#rental-dialog").showModal()}
async function save(e){e.preventDefault();calculateDeposit();const f=e.currentTarget,v=n=>f.elements.namedItem(n).value.trim(),number=n=>v(n)?Number(v(n)):null;if(!v("cliente_id")||!v("carro_id")||!v("data_inicio"))return toast("Informe locatário, carro e início.",true);const payload={cliente_id:v("cliente_id"),carro_id:v("carro_id"),data_inicio:v("data_inicio"),data_fim:v("data_fim")||null,valor_diaria:number("valor_diaria"),status:v("status"),valor_caucao:number("valor_caucao"),valor_caucao_pago:number("valor_caucao_pago")??0,saldo_caucao:number("saldo_caucao")??0,numero_parcelas_caucao:number("numero_parcelas_caucao")??100,valor_parcela_caucao:number("valor_parcela_caucao")??0,multa_atraso_percentual:number("multa_atraso_percentual")??11,observacoes:v("observacoes")||null};const q=state.editing?db.from("locacoes").update(payload).eq("id",state.editing):db.from("locacoes").insert(payload),{error}=await q;if(error)return toast(error.message,true);$("#rental-dialog").close();toast("Locação salva com os dados do contrato.");await load()}
$("#new-rental").onclick=()=>open();$("#refresh-rentals").onclick=load;$("#rental-search").oninput=render;$("#rental-status").onchange=render;$("#rental-form").onsubmit=save;$("#rental-car").onchange=e=>{const c=state.cars.find(x=>x.id===e.target.value);if(c){$("#rental-form").elements.valor_diaria.value=c.valor_diaria??"";$("#rental-form").elements.valor_caucao.value=c.caucao??"";calculateDeposit()}};for(const name of["valor_caucao","valor_caucao_pago","numero_parcelas_caucao","valor_diaria"])$("#rental-form").elements[name].addEventListener("input",calculateDeposit);for(const id of["#close-rental","#cancel-rental"])$(id).onclick=()=>$("#rental-dialog").close();await load();
