import {createClient} from "https://esm.sh/@supabase/supabase-js@2"; import {requireAuth,bindLogout} from "./auth-guard.js";
const db=createClient("https://xtelzwclrzzlsqjecscl.supabase.co","sb_publishable_37VAv7_GhtRLum-WVwMv0w_EiD0HqZ3"); await requireAuth(db); bindLogout(db);
const $=s=>document.querySelector(s),state={rows:[],clients:[],cars:[],editing:null,inspections:[],inspectionError:false,events:[],eventsError:false,operating:null}; let timer;
const money=n=>n==null?"—":Number(n).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}); const date=d=>d?new Date(d).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—";
function toast(t,e=false){const x=$("#toast");x.textContent=t;x.classList.toggle("error",e);x.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>x.classList.remove("show"),4000)}
function fill(el,rows,label){el.replaceChildren(new Option("Selecione",""));rows.forEach(x=>el.add(new Option(label(x),x.id)))}
function clientName(id){return state.clients.find(x=>x.id===id)?.nome_completo||"Cliente indisponível"} function carName(id){const x=state.cars.find(x=>x.id===id);return x?`${x.placa} · ${x.marca||""} ${x.modelo||""}`:"Carro indisponível"}
const plain=v=>v==null?"":String(v); const brl=v=>v==null?"":Number(v).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
function calculateDeposit(){const f=$("#rental-form"),num=name=>Number(f.elements.namedItem(name)?.value)||0,total=Math.max(0,num("valor_caucao")),paid=Math.min(Math.max(0,num("valor_caucao_pago")),total),installments=Math.max(1,Math.trunc(num("numero_parcelas_caucao")||100)),balance=Math.max(0,total-paid),installment=balance/installments,daily=Math.max(0,num("valor_diaria"));f.elements.valor_caucao_pago.value=paid.toFixed(2);f.elements.saldo_caucao.value=balance.toFixed(2);f.elements.numero_parcelas_caucao.value=installments;f.elements.valor_parcela_caucao.value=installment.toFixed(2);f.elements.valor_diaria_com_caucao.value=(daily+installment).toFixed(2)}

function rentalFlow(row, inspections, unavailable=false, now=Date.now()) {
  const contract='contrato.html?locacao='+encodeURIComponent(row.id), records='registros.html?locacao='+encodeURIComponent(row.id);
  const result=(stage,note,action,url=contract)=>({stage,note,action,url});
  if(row.status==='Cancelada')return result('Cancelada','Locação cancelada.','Ver registros',records);
  if(row.status==='Encerrada')return result('Encerrada','Confira os documentos e valores registrados.','Ver registros',records);
  if(row.__returned)return result('Conferir encerramento','Devolução confirmada. O administrador deve conferir valores e caução.','Ver registros',records);
  if(unavailable)return result('Verificar dados','Não foi possível consultar as vistorias. Atualize para tentar novamente.','Conferir vistoria');
  const complete=v=>v&&v.data_hora&&v.responsavel&&v.quilometragem!=null&&v.combustivel&&v.condicao_geral;
  const own=inspections.filter(v=>v.locacao_id===row.id), departure=own.find(v=>v.tipo==='saida'), returned=own.find(v=>v.tipo==='devolucao');
  const due=row.status==='Ativa'&&row.data_fim&&new Date(row.data_fim).getTime()<=now;
  if(due)return complete(returned)?result('Conferir encerramento','Vistoria de retorno preenchida. Confira valores, caução e documentos antes de encerrar.','Ver registros',records):result('Devolução prevista','Prazo previsto atingido. Confirme a devolução e preencha a vistoria de retorno.','Preparar devolução');
  if(row.__delivered)return result('Em andamento','Entrega confirmada. Acompanhe a locação e registre a devolução quando ocorrer.','Ver registros',records);
  if(!complete(departure))return result('Preparar entrega','Preencha responsável, data, km, combustível e condição geral na vistoria de saída. Confira checklist e fotos.','Preencher vistoria');
  if(!row.contrato_gerado_em)return result('Gerar contrato','Vistoria preenchida. Revise o modelo, checklist e imagens antes de gerar o PDF.','Preparar contrato');
  const signed=Boolean(row.assinatura_locadora_em&&row.assinatura_cliente_em);
  if(!signed)return result('Acompanhar assinatura',row.assinatura_referencia?'Enviado. Aguardando confirmação das assinaturas.':'PDF definitivo pronto para envio. Envie o documento salvo para assinatura.',row.assinatura_referencia?'Conferir assinatura':'Enviar para assinatura','assinaturas.html?locacao='+encodeURIComponent(row.id));
  if(row.status==='Reservada')return result('Confirmar entrega','Assinaturas registradas. Confirme a entrega do veículo antes de iniciar a locação.','Ver registros',records);
  return result('Em andamento','Acompanhe documentos, valores registrados e a data prevista de devolução.','Ver registros',records);
}

function render(){const search=$("#rental-search");let q=search.value.toLocaleLowerCase("pt-BR");if(q.trim()==="alquilerentcar@gmail.com"){q="";search.value=""}const stage=$("#rental-stage").value,s=$("#rental-status").value,rows=state.rows.filter(x=>(s==="todos"||x.status===s)&&(stage==="todos"||rentalFlow(x,state.inspections,state.inspectionError).stage===stage)&&`${clientName(x.cliente_id)} ${carName(x.carro_id)}`.toLocaleLowerCase("pt-BR").includes(q));$("#rental-total").textContent=state.rows.length;$("#rental-active").textContent=state.rows.filter(x=>x.status==="Ativa").length;$("#rental-reserved").textContent=state.rows.filter(x=>x.status==="Reservada").length;$("#rental-closed").textContent=state.rows.filter(x=>x.status==="Encerrada").length;$("#rental-count").textContent=`${rows.length} de ${state.rows.length} locações`;const b=$("#rental-body");b.replaceChildren();for(const x of rows){const tr=document.createElement("tr");const clientCell=document.createElement("td"),clientLink=document.createElement("button");clientLink.className="record-link";clientLink.textContent=clientName(x.cliente_id);clientLink.onclick=()=>location.href=`registros.html?locacao=${encodeURIComponent(x.id)}`;clientCell.append(clientLink);tr.append(clientCell);for(const v of[carName(x.carro_id),date(x.data_inicio),date(x.data_fim),money(x.valor_diaria),money(x.valor_pago),x.status]){const td=document.createElement("td");td.textContent=v;tr.append(td)}const flow=rentalFlow(x,state.inspections,state.inspectionError),cell=document.createElement("td"),label=document.createElement("strong"),note=document.createElement("p");label.textContent=flow.stage;note.textContent=flow.note;note.className="flow-note";cell.append(label,note);tr.append(cell);const a=document.createElement("td");a.className="table-actions";const next=document.createElement("button");next.textContent=flow.action;next.onclick=()=>location.href=flow.url;a.append(next);const records=document.createElement("button");records.textContent="Ver registros";records.onclick=()=>location.href=`registros.html?locacao=${encodeURIComponent(x.id)}`;a.append(records);const manage=document.createElement("button");manage.textContent="Gerenciar etapas";manage.disabled=state.eventsError;manage.onclick=()=>openOperation(x);a.append(manage);tr.append(a);b.append(tr)}$("#rental-empty").classList.toggle("hidden",rows.length>0)}
async function load(){const[rs,cs,vs,ins,events]=await Promise.all([db.from("locacoes").select("*").order("criado_em",{ascending:false}),db.from("clientes").select("id,nome_completo,situacao").order("nome_completo"),db.from("carros").select("*").order("placa"),db.from("vistorias_locacao").select("locacao_id,tipo,data_hora,responsavel,quilometragem,combustivel,condicao_geral"),db.from("locacao_eventos").select("locacao_id,acao,criado_em,usuario_id,dados").order("criado_em")]);const e=rs.error||cs.error||vs.error;if(e)return toast(e.message,true);state.events=events.data||[];state.eventsError=Boolean(events.error);$("#operation-warning").hidden=!events.error;state.inspections=ins.data||[];state.inspectionError=Boolean(ins.error);if(ins.error)toast("Não foi possível consultar as vistorias. As etapas não puderam ser verificadas.",true);state.rows=(rs.data||[]).map(row=>({...row,__delivered:state.events.some(e=>e.locacao_id===row.id&&e.acao==="entrega"),__returned:state.events.some(e=>e.locacao_id===row.id&&e.acao==="devolucao")}));state.clients=cs.data||[];state.cars=vs.data||[];fill($("#rental-client"),state.clients,x=>x.nome_completo);fill($("#rental-car"),state.cars,x=>carName(x.id));render()}
function open(){state.editing=null;const f=$("#rental-form");f.reset();$("#rental-dialog-title").textContent="Nova locação";f.elements.data_inicio.value=localNow();f.elements.multa_atraso_percentual.value="11";f.elements.numero_parcelas_caucao.value="100";f.elements.valor_caucao_pago.value="0";calculateDeposit();$("#rental-dialog").showModal()}
async function save(e){e.preventDefault();calculateDeposit();const f=e.currentTarget,v=n=>f.elements.namedItem(n).value.trim(),number=n=>v(n)?Number(v(n)):null;if(!v("cliente_id")||!v("carro_id")||!v("data_inicio"))return toast("Informe locatário, carro e início.",true);const payload={cliente_id:v("cliente_id"),carro_id:v("carro_id"),data_inicio:v("data_inicio"),data_fim:v("data_fim")||null,valor_diaria:number("valor_diaria"),status:v("status"),valor_caucao:number("valor_caucao"),valor_caucao_pago:number("valor_caucao_pago")??0,saldo_caucao:number("saldo_caucao")??0,numero_parcelas_caucao:number("numero_parcelas_caucao")??100,valor_parcela_caucao:number("valor_parcela_caucao")??0,multa_atraso_percentual:number("multa_atraso_percentual")??11,observacoes:v("observacoes")||null};const q=state.editing?db.from("locacoes").update(payload).eq("id",state.editing):db.from("locacoes").insert(payload),{error}=await q;if(error)return toast(error.message,true);$("#rental-dialog").close();toast("Locação salva com os dados do contrato.");await load()}
$("#new-rental").onclick=()=>open();$("#refresh-rentals").onclick=load;$("#rental-search").oninput=render;$("#rental-status").onchange=render;$("#rental-stage").onchange=render;$("#rental-form").onsubmit=save;$("#rental-car").onchange=e=>{const c=state.cars.find(x=>x.id===e.target.value);if(c){$("#rental-form").elements.valor_diaria.value=c.valor_diaria??"";$("#rental-form").elements.valor_caucao.value=c.caucao??"";calculateDeposit()}};for(const name of["valor_caucao","valor_caucao_pago","numero_parcelas_caucao","valor_diaria"])$("#rental-form").elements[name].addEventListener("input",calculateDeposit);for(const id of["#close-rental","#cancel-rental"])$(id).onclick=()=>$("#rental-dialog").close();await load();


function openOperation(row){
 state.operating=row;const form=$("#operation-form");form.reset();
 $("#operation-title").textContent=clientName(row.cliente_id)+' · '+carName(row.carro_id);
 const events=state.events.filter(e=>e.locacao_id===row.id),history=$("#operation-history");history.replaceChildren();
 const labels={entrega:'Entrega confirmada',devolucao:'Devolução confirmada',encerramento:'Encerramento confirmado'};
 for(const event of events){const item=document.createElement('p');item.textContent=labels[event.acao]+' · '+date(event.criado_em)+' · '+(event.dados?.observacoes||'')+' · Responsável (ID): '+event.usuario_id;history.append(item);}
 if(!events.length)history.textContent='Nenhuma confirmação registrada neste fluxo. O status anterior da locação foi preservado.';
 const action=row.status==='Reservada'?'entrega':row.status==='Ativa'?(row.__returned?'encerramento':'devolucao'):'';
 form.dataset.action=action;
 for(const field of form.querySelectorAll('[data-operation]')){const visible=field.dataset.operation.split(' ').includes(action);field.hidden=!visible;for(const input of field.querySelectorAll('input')){input.disabled=!visible;input.required=visible;}}
 const admin=Boolean(window.alquilerContext?.canManageCompany),allowed=action&&(action!=='encerramento'||admin);
 $("#operation-confirm").hidden=!allowed;form.elements.observacoes.disabled=!allowed;
 $("#operation-confirm").textContent={entrega:'Confirmar entrega',devolucao:'Confirmar devolução',encerramento:'Encerrar locação'}[action]||'Confirmar';
 $("#operation-guidance").textContent=action==='entrega'?'Preencha a vistoria de saída, gere o PDF e confira as assinaturas antes de confirmar a entrega física.':action==='devolucao'?'No contrato, selecione a vistoria Devolução, preencha os dados e salve. Confirme aqui quando o veículo tiver sido devolvido. A locação ficará ativa até o encerramento.':action==='encerramento'?(admin?'Confira os valores finais, pagamentos e destinação da caução. Esta declaração não registra pagamentos nem gera distrato automaticamente.':'O administrador deve conferir os valores e encerrar esta locação.'):'Esta locação não possui novas ações disponíveis.';
 $("#operation-inspection").textContent=row.contrato_gerado_em?"Ver PDF definitivo e assinatura":"Editar contrato e vistoria";$("#operation-inspection").href=(row.contrato_gerado_em?'assinaturas.html?locacao=':'contrato.html?locacao=')+encodeURIComponent(row.id);$("#operation-records").href='registros.html?locacao='+encodeURIComponent(row.id);
 $("#operation-error").textContent='';let subsequent=$("#operation-subsequent");if(!subsequent){subsequent=document.createElement("a");subsequent.id="operation-subsequent";subsequent.className="btn btn-quiet";subsequent.textContent="Registrar vistoria posterior";$("#operation-inspection").parentElement.append(subsequent);}subsequent.hidden=!(row.contrato_gerado_em&&row.status==="Ativa");subsequent.href="contrato.html?locacao="+encodeURIComponent(row.id);$("#operation-dialog").showModal();
}
$("#operation-close").onclick=()=>$("#operation-dialog").close();
$("#operation-form").onsubmit=async event=>{
 event.preventDefault();const form=event.currentTarget,button=$("#operation-confirm");if(!form.reportValidity())return;button.disabled=true;$("#operation-error").textContent='';
 try{const data={observacoes:form.elements.observacoes.value.trim()};for(const name of ['vistoria_conferida','assinatura_conferida','financeiro_conferido','caucao_conferida'])data[name]=!form.elements[name].disabled&&form.elements[name].checked;
 const {error}=await db.rpc('locacao_confirmar_etapa',{p_empresa:window.alquilerContext.company.id,p_locacao:state.operating.id,p_acao:form.dataset.action,p_dados:data});
 if(error)throw error;$("#operation-dialog").close();await load();toast('Etapa confirmada e registrada no histórico.');
 }catch(error){$("#operation-error").textContent=error.message||'Não foi possível confirmar a etapa.';}finally{button.disabled=false;}
};
