import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {requireAuth,bindLogout} from './auth-guard.js';
import {documentKind} from './document-kind.mjs';
const db=createClient('https://xtelzwclrzzlsqjecscl.supabase.co','sb_publishable_37VAv7_GhtRLum-WVwMv0w_EiD0HqZ3');
await requireAuth(db);bindLogout(db);
const section=location.pathname.split('/').pop().replace(/\.html$/,''),context=window.alquilerContext;
if(['recibos','alteracoes','distratos'].includes(section)){
 const node=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};
 const panel=document.querySelector('.panel');panel.replaceChildren();const header=node('div','','panel-top'),title=node('h2','Documentos emitidos'),refresh=node('button','Atualizar','btn btn-quiet');refresh.type='button';header.append(title,refresh);panel.append(header);
 const content=node('div','','dialog-body'),models=node('div','','models3-buttons');content.append(models);panel.append(content);
 for(const m of context.documentModels||[])if(documentKind(m)===section){const a=node('a','Preparar '+m.nome,'btn btn-quiet');a.href='documentos-modelo.html?modelo='+encodeURIComponent(m.id);models.append(a);}
 const filters=node('div','','document-filters'),search=node('input'),kind=node('select'),from=node('input'),until=node('input');search.type='search';search.placeholder='Buscar pessoa, veículo ou descrição';search.autocomplete='off';search.setAttribute('data-lpignore','true');search.setAttribute('aria-label','Pesquisar documentos');
 for(const [value,label] of [['registro','Data de registro'],['contrato','Data do contrato']]){const o=node('option',label);o.value=value;kind.append(o);}
 kind.setAttribute('aria-label','Tipo de data');from.type=until.type='date';from.setAttribute('aria-label','Data inicial');until.setAttribute('aria-label','Data final');filters.append(search,kind,from,until);content.append(filters);
 const status=node('p','Carregando…');status.setAttribute('role','status');content.append(status);const scroll=node('div','','table-scroll'),table=node('table'),thead=node('thead'),body=node('tbody'),tr=node('tr');
 const headings=section==='recibos'?['Pessoa','Valor','Referente a','Registro','Contrato','Ações']:section==='alteracoes'?['Pessoa','Veículo anterior','Veículo posterior','Data da troca','Motivo / descrição','Registro','Ações']:['Pessoa','Locação','Veículos utilizados','Descrição','Registro','Contrato','Ações'];
 for(const h of headings)tr.append(node('th',h));thead.append(tr);table.append(thead,body);scroll.append(table);panel.append(scroll);
 let docs=[],rentals=[],clients=[],cars=[],allChanges=[];
 const stamp=v=>!v?'Não registrado':Number.isNaN(new Date(v).getTime())?String(v):new Date(v).toLocaleDateString('pt-BR'),missing='Não registrado',lookup=(a,id,key)=>a.find(x=>x.id===id)?.[key],money=v=>v===undefined||v===null?missing:typeof v==='string'&&!/^\d+(\.\d+)?$/.test(v.trim())?v:Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 function render(){body.replaceChildren();const q=search.value.trim().toLocaleLowerCase('pt-BR');let count=0;
  for(const d of docs){const r=rentals.find(x=>x.id===d.locacao_id)||{},v=d.valores||d.provider_payload?.recibo||{},person=lookup(clients,r.cliente_id,'nome_completo')||v.cliente_nome||v.locatario_nome||v.nome_locatario||missing,contract=r.data_inicio,day=(kind.value==='registro'?d.criado_em:contract);const dateKey=day?new Date(day).toLocaleDateString('en-CA',{timeZone:'America/Manaus'}):'';
   const description=v.descricao||v.referente_a||v.descricao_pagamento||v.condicoes_encerramento||d.nome,values=section==='recibos'?[person,money(v.valor_total??v.valor_recebido??(v.valor_unitario!==undefined?v.valor_unitario*Number(v.quantidade||1):v.valor)),description,stamp(d.criado_em),stamp(contract)]:section==='alteracoes'?[person,v.veiculo_anterior||v.carro_anterior||v.veiculo_placa||missing,v.veiculo_posterior||v.carro_posterior||v.nova_placa||missing,stamp(v.data_troca||v.data_alteracao),v.motivo||v.motivo_alteracao||description,stamp(d.criado_em)]:[person,r.contrato_numero||d.locacao_id||missing,v.carros_usados||[...new Set([lookup(cars,r.carro_id,'placa'),...allChanges.filter(x=>x.locacao_id===d.locacao_id).flatMap(x=>[x.valores?.veiculo_placa,x.valores?.nova_placa])].filter(Boolean))].join(' → ')||missing,description,stamp(d.criado_em),stamp(contract)];
   if(!values.join(' ').toLocaleLowerCase('pt-BR').includes(q)||(from.value&&(!dateKey||dateKey<from.value))||(until.value&&(!dateKey||dateKey>until.value)))continue;count++;const row=node('tr');for(const value of values)row.append(node('td',String(value)));const actions=node('td','','table-actions');
   if(d.path){const button=node('button','Abrir PDF','btn btn-quiet');button.type='button';button.onclick=async()=>{button.disabled=true;try{const result=await db.storage.from(d.bucket).createSignedUrl(d.path,600);if(result.error)throw result.error;let link=actions.querySelector('a[data-pdf]');if(!link){link=node('a','Visualizar PDF','btn btn-quiet');link.dataset.pdf='true';link.target='_blank';link.rel='noopener';actions.append(link);}link.href=result.data.signedUrl;link.focus();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};actions.append(button);}
   if(d.locacao_id){const a=node('a','Ver locação','btn btn-quiet');a.href='registros.html?locacao='+encodeURIComponent(d.locacao_id);actions.append(a);}row.append(actions);body.append(row);
  }status.textContent=count+' de '+docs.length+' documentos'+(!count?' · Nenhum resultado.':'');
 }
 async function load(){refresh.disabled=true;try{const versions=await db.from('versoes_modelos_documentos').select('id,nome').eq('empresa_id',context.company.id);if(versions.error)throw versions.error;const ids=(versions.data||[]).filter(v=>documentKind(v)===section).map(v=>v.id);
  const results=await Promise.all([ids.length?db.from('documentos_modelos_emitidos').select('*').eq('empresa_id',context.company.id).in('versao_id',ids):Promise.resolve({data:[]}),db.from('documentos_locacao').select('*').in('tipo',section==='recibos'?['outro']:section==='alteracoes'?['alteracao_veiculo']:['distrato']),db.from('locacoes').select('*'),db.from('clientes').select('id,nome_completo'),db.from('carros').select('id,placa'),section==='distratos'?db.from('documentos_modelos_emitidos').select('locacao_id,valores').eq('empresa_id',context.company.id):Promise.resolve({data:[]})]);for(const result of results)if(result.error)throw result.error;
  docs=[...(results[0].data||[]).map(d=>({...d,bucket:'documentos-modelos',path:d.arquivo_path})),...(results[1].data||[]).filter(d=>section!=='recibos'||documentKind(d)==='recibos').map(d=>({...d,bucket:'documentos-contratuais',path:d.arquivo_assinado_path||d.arquivo_original_path}))].sort((a,b)=>new Date(b.criado_em)-new Date(a.criado_em));rentals=results[2].data||[];clients=results[3].data||[];cars=results[4].data||[];allChanges=results[5].data||[];render();
 }catch(e){status.textContent='Não foi possível carregar os documentos: '+e.message;}finally{refresh.disabled=false;}}
 search.oninput=render;kind.onchange=from.onchange=until.onchange=render;refresh.onclick=load;await load();
}
